# Container-based https://docs.travis-ci.com/user/ci-environment/
sudo: false

language: android

# The default oraclejdk7 doesn't work
jdk:
  - oraclejdk8

android:
  components:
    - tools # Update preinstalled tools
    - build-tools-25.0.3
    - android-25
    - platform-tools
    - tools # Update tools

# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    # Android tools path
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}

install:
  # Accept ConstraintLayout license
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

script:
  # Customized build without tests for now
  - ./gradlew build
